---
- hosts: "{{ execution_host }}"
  name: "Creating the new work environment"
  vars_files:
    - "vars/machine-config.yml"
  tasks:
    - name: "Install packages using apt"
      include_tasks: "{{ ansible_install_folder }}/package-manager.yml"

    - name: "Downloading dotfiles repository to personal directory"
      include_tasks: "{{ ansible_install_folder }}/download-dotfiles.yml"

    - name: "Copy fonts"
      include_tasks: "{{ ansible_install_folder }}/fonts.yml"

    - name: "Install kitty terminal"
      include_tasks: "{{ ansible_install_folder }}/kitty.yml"

    - name: "Install oh my zsh"
      include_tasks: "{{ ansible_install_folder }}/zsh.yml"

    - name: "Install Docker"
      include_tasks: "{{ ansible_install_folder }}/docker.yml"

    - name: "Create link with .vimrc"
      include_tasks: "{{ ansible_config_folder }}/vim.yml"

    - name: "Create link with .tmux.conf"
      include_tasks: "{{ ansible_config_folder }}/tmux.yml"

    - name: "Copy and decrypt private and public keys"
      include_tasks: "{{ ansible_config_folder }}/ssh.yml"

    - name: "Copy and decrypt git config files"
      include_tasks: "{{ ansible_config_folder }}/git.yml"

    - name: "Create link with i3 config files"
      include_tasks: "{{ ansible_config_folder }}/i3.yml"

    - name: "Download wallpapers folder"
      include_tasks: "{{ ansible_install_folder }}/wallpapers.yml"

    - name: "Create link with rofi config files"
      include_tasks: "{{ ansible_config_folder }}/rofi.yml"

    - name: "Create link with kitty config files"
      include_tasks: "{{ ansible_config_folder }}/kitty.yml"
