---
- name: "Copy i3 conf file to personal folder"
  ansible.builtin.file:
    src: "{{ personal_folder }}/dotfiles/i3/config"
    path: "{{ config_folder }}/i3/"
    state: "link"
    mode: "0664"
    force: true
