---
- name: "Copy vimrc to personal folder"
  ansible.builtin.file:
    src: "{{ projects_folder }}/dotfiles/vim/.vimrc"
    path: "{{ personal_folder }}/.vimrc"
    state: "link"
    mode: "0664"
    force: true
