---
- name: "Copy zshrc to personal folder"
  ansible.builtin.file:
    src: "{{ projects_folder }}/dotfiles/zsh/.zshrc"
    path: "{{ personal_folder }}/.zshrc"
    state: "link"
    mode: "0664"
    force: true
