---
execution_host: "192.168.1.41"
personal_user: "joan"
personal_folder: "/home/{{ personal_user }}"
projects_folder: "{{ personal_folder }}/Projects"
config_folder: "{{ personal_folder }}/.config"
share_folder: "{{ personal_folder }}/.local/share"
bin_folder: "/usr/local/bin"
ansible_install_folder: "install-packages"
ansible_config_folder: "config-packages"
