---

- name: Validate Composer checksum
  get_url:
    checksum: "sha384:55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae"
    dest: /tmp/
    url: https://getcomposer.org/installer

- name: Download and install Composer
  shell: curl -sS https://getcomposer.org/installer | php
  args:
    chdir: /tmp/
    creates: /tmp/composer
    warn: false

- name: Add Composer to global path
  copy:
    dest: /usr/local/bin/composer
    group: root
    mode: '0755'
    owner: root
    src: /tmp/composer.phar
    remote_src: true
  become: true
