---
- name: "Find all files in dotfiles/fonts"
  ansible.builtin.find:
    paths: "{{ projects_folder }}/dotfiles/fonts"
  register: "find"

- name: "Creates directory if not exists"
  ansible.builtin.file:
    path: "{{ share_folder }}/fonts/"
    state: "directory"

- name: "Create symlinks to .local/share/fonts/"
  become: false
  ansible.builtin.file:
    src: "{{ item.path }}"
    path: "{{ share_folder }}/fonts/{{ item.path | basename }}"
    state: "link"
    force: true
  with_items: "{{ find.files }}"

