---
- name: "install nvim prerequisites"
  become: true
  become_user: "root"
  when: ansible_facts['os_family'] == "Debian"
  apt:
    update_cache: "yes"
    state: "latest"
    name:
      - "ninja-build"
      - "gettext"
      - "libtool"
      - "libtool-bin"
      - "autoconf"
      - "automake"
      - "cmake"
      - "g++"
      - "pkg-config"
      - "unzip"
      - "curl"
      - "doxygen"

- name: "Download nvim source code"
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim"
    dest: "{{ personal_folder }}/source/nvim"
    version: "stable"
    force: true


- name: Create a directory .deps if it does not exist
  ansible.builtin.file:
    path: "{{ personal_folder }}/source/nvim/.deps"
    state: directory
    mode: '0755'

- name: Create a directory build if it does not exist
  ansible.builtin.file:
    path: "{{ personal_folder }}/source/nvim/build"
    state: directory
    mode: '0755'

- name: "Execute build"
  become: true
  ansible.builtin.command:
    chdir: "{{ personal_folder }}/source/nvim"
    cmd: "make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=/usr/local install"
