---
- name: "Install pip packages"
  ansible.builtin.pip:
    state: "latest"
    name:
      - "bumblebee-status"
      - "tk"
      - "psutil"
      - "dbus-python"
      - "iw"
      - "netifaces"
    extra_args: "--user"
